### ISSUE TITLE
Multiline Remark does not get colored correctly

### ISSUE THREAD

**Issue by icegoogles** [alek5k/TPSyntaxHighlighter#4]
Hey, great VS Code extension :)
I found a small issue, that "Multiline Remarks" do not get colored (white). Other Remarks get colored green.
![Screenshot 2024-04-08 142845](https://github.com/alek5k/TPSyntaxHighlighter/assets/44415544/c65c5902-b26f-4124-ac40-ecc4b539b840)
_(Example not 100% correct, see better example below)_

**Expected behaviour:**
Both get colored the same (or similar) color

**Comment by icegoogles** [comment]
It should be as simple as adding the following code segment
```xml
<!-- multiline comment -->
            <dict>
                <key>match</key>
                <string>\s*:\s*--.*--\s?;</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
```

**Comment by alek5k** [comment]
[Edit: See comment below]

Hi there @icegoogles 

Thanks for the info. It's been a while since I worked on this (so things may have changed), but from memory there was a problem with grammars that span multiple lines. The highlighting engine is called "text mate" and there is a limitation on multi-line highlighting, see here:

https://github.com/microsoft/vscode-textmate/issues/41#issuecomment-344294298

So while your regex does work if the multiline style comment is on a single line, it wont work if you break it up into multiple lines. There may be some workarounds floating around somewhere.

Is it good enough to highlight a single line for your usage? Otherwise, do you have some examples of multi-line comments that can be used to test updated grammars?

**Comment by alek5k** [comment]
@icegoogles I updated the language syntax to use json instead of the older style XML format, which seems a bit more flexible in allowing multiple lines. Does this match your expectation in how multiline comments should look?

![image](https://github.com/alek5k/TPSyntaxHighlighter/assets/20435565/91fa4396-4949-498b-a80a-e55e79d3a1e9)

**Comment by icegoogles** [comment]
Thanks for the answer and indeed I forgot about the possibility, that the multiline wraps around in the source file. I tought it would only be done inside the teach pendant. Here is one example I made to capture both possibilities. Obviously there could be more or less line changes in the "second line"

![fanucPOV](https://github.com/alek5k/TPSyntaxHighlighter/assets/44415544/2e152e57-d762-4714-b8d4-b448d5952723)
![VsCodePOV](https://github.com/alek5k/TPSyntaxHighlighter/assets/44415544/392d54d5-4ce6-404e-a15e-160e7f66efd5)
VsCode Text as Code instead of as image
```
   1:  !Normal Remark xxxxxxxxxxxxxxxxxx ;
   2:  --eg:Multiline Remark test test test test test test test test test test
    :  test test test test test test test test test test test test test test
    :  test test test test test test test test test test test test test test
    :  test test test test test test tests ;
   3:  --eg:Multiline short ;
```

**Also:** It seems that "--eg:" is the identfier. Not just "--". I falsely tought the "eg:" was in the original comment

**Comment by alek5k** [comment]
@icegoogles thanks for following up

That's interesting. I wonder if the "eg:" is added in by Fanuc. For instance, in VSCode, you actually dont need to put line numbers, but it's still valid TP code and once you transfer to teach pendant, the line numbers get added in. The same could be the case for the "eg".

Could you perhaps put a multiline remark in vscode without using eg:, then transfer to the teach pendant, then download from the teach pendant and see what the output is?

I'm trying to figure out whether we need to support both `--` and `--eg`, or just `--eg`

**Comment by icegoogles** [comment]
I deleted the `eg:` and did reload it into the controller. This did work. Downloading from the controller added the `eg:` again, as you suspected

**Comment by alek5k** [comment]
Hey @icegoogles, appreciate your help with this :)

I've updated the extension on the VSCode marketplace with the changes, see below on the VSCode store:

https://marketplace.visualstudio.com/items?itemName=alekskrnjaic.fanuctplanguage

The newest version is `v0.11.0` and should be available through extension tab in VSCode:

![image](https://github.com/alek5k/TPSyntaxHighlighter/assets/20435565/7529238a-0acc-4214-b9f7-7f91be62b472)

**Comment by icegoogles** [comment]
My pleasure. Thanks vor the very fast fix :)
